# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme

# Site settings
title: The home of IPMI tools
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Announcements and general information about
  the collection of IPMI tools (ipmitool, frugen, etc.)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ipmitool.github.io" # the base hostname & protocol for your site
github_username: AlexanderAmelkin

# Build settings
markdown: kramdown
